language: node_js
node_js:
  - "6.1"
  - "6.0"
  - "5.11"
  - "5.10"
  - "5.7"
  - "5.3"
  - "5.0"
  - "4.4"
  - "4.1"
  - "4.0"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y imagemagick  graphicsmagick python2.7
before_script:
  - npm install -g node-gyp
  - node build.js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8